### ISSUE TITLE
Disable on user settings

### ISSUE THREAD

**Issue by 3DDario** [odubuc/mysql-inline-decorator#1]
![image](https://user-images.githubusercontent.com/6069723/32663643-087d6504-c62f-11e7-8420-eee1f9ada0d8.png)

**Comment by odubuc** [comment]
Good point. I'll look into it.

**Comment by odubuc** [comment]
I just published an update that exclude json files. 
I'll close this issue but if anything is wrong with your configuration files simply let me know in here and I'll have another look. sorry for the delay, I've been busy on another project :)
