### ISSUE TITLE
Bug syntax highlighting PHP

### ISSUE THREAD

**Issue by sebtiz13** [odubuc/mysql-inline-decorator#3]
Hello i have bug with your plugin in php he break the syntax highlighting of PHP.
I think the search intervals between backticks is too excessive.

For exemple in this file the first interval count 294 lines (Line 129 to 423)
https://github.com/erusev/parsedown/blob/1.7.1/Parsedown.php

![screenshot](https://user-images.githubusercontent.com/1382368/39549202-487918a4-4e5d-11e8-91eb-1aeb6da9f5e4.png)

**Comment by odubuc** [comment]
I'll have a look at it!
